### ISSUE TITLE
Build errors due to SOIL

### ISSUE THREAD

**Issue by JT8D-17** [skiselkov/librain#36]
> ../../src/objmgr.c:19:10: fatal error: SOIL/SOIL.h: No such file or directory
>   19 | #include <SOIL/SOIL.h>
>      |          ^~~~~~~~~~~~~
>compilation terminated.

A local installation with a modified qmake.pro file produces this error:

> /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: debug/objmgr.o: in function `complete_texture_load':
/media/Simulators/0_Git_Repos/librain/plugin/qmake/../../src/objmgr.c:195: undefined reference to `SOIL_load_OGL_texture_from_memory'

How is SOIL integration supposed to be handled to satisfy compiler requirements?

**Comment by toadlife** [comment]
I'm stuck on this too. :(

**Comment by toadlife** [comment]
> > ../../src/objmgr.c:19:10: fatal error: SOIL/SOIL.h: No such file or directory
> > 19 | #include <SOIL/SOIL.h>
> > |          ^~~~~~~~~~~~~
> > compilation terminated.
> 
> A local installation with a modified qmake.pro file produces this error:
> 
> > /usr/lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld: debug/objmgr.o: in function `complete_texture_load': /media/Simulators/0_Git_Repos/librain/plugin/qmake/../../src/objmgr.c:195: undefined reference to `SOIL_load_OGL_texture_from_memory'
> 
> How is SOIL integration supposed to be handled to satisfy compiler requirements?

I figured it out. Aside from linking to SOIL.h, you need to statically link to a pre-built mingw version of the SOIL library. Instead of trying to build it myself, I used this package: [https://packages.msys2.org/package/mingw-w64-x86_64-soil](https://packages.msys2.org/package/mingw-w64-x86_64-soil)
I extracted the package into the libacfutils directory and then altered the qmake.pro file to statically link to it.

Here are the lines from my qmake.pro file where you link it. SOIL has to be linked _before_ glu32 and opengl32 :

```
LIBS += -L$$[LIBACFUTILS]/SDK/Libraries/Win -lXPLM_64
LIBS += -L$$[LIBACFUTILS]/soil/lib -lSOIL
LIBS += -L$$[LIBACFUTILS]/GL_for_Windows/lib -lglu32 -lopengl32
```

**Comment by JT8D-17** [comment]
For Linux, it suffices to install a package providing SOIL (`soil` on Arch).
